import type { Category, WordEntry, WordSource } from "../data/types";
import { WORD_LIBRARY, TLDS } from "../data/word-pools";
import { fusePair, type FusionVariant } from "./fusion";
import { scoreName } from "./scoring";
export type Blend={id:string;name:string;a:string;b:string;method:string;tld:string;score:number;categories:Category[];sourcesA:WordSource[];sourcesB:WordSource[]};
export type GenOptions={categories:Category[];sources:WordSource[];minLen:number;maxLen:number;count:number;seedA?:string;seedB?:string;tlds:string[]};
const pickWeighted=<T extends {weight:number}>(items:T[])=>{if(!items.length)return null;const total=items.reduce((s,i)=>s+i.weight,0);let roll=Math.random()*total;for(const i of items){roll-=i.weight;if(roll<=0)return i}return items[items.length-1]};
const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
function library(opts:GenOptions){const sources=new Set(opts.sources),cats=new Set(opts.categories);return WORD_LIBRARY.filter(e=>e.sources.some(s=>sources.has(s))&&(!cats.size||e.categories.some(c=>cats.has(c))));}
function customEntry(word:string,selected:WordEntry[]){const w=word.toLowerCase().replace(/[^a-z]/g,"");return selected.find(e=>e.word===w)||{word:w,categories:["abstract"],sources:[],weight:.75};}
function variants(a:WordEntry,b:WordEntry){const one=fusePair(a.word,b.word),two=fusePair(b.word,a.word).map(v=>({...v,method:`reverse-${v.method}`}));const seen=new Set<string>();return[...one,...two].filter(v=>{if(seen.has(v.name))return false;seen.add(v.name);return true});}
export function generate(opts:GenOptions):Blend[]{const count=Math.max(6,Math.min(120,opts.count));const minLen=Math.min(opts.minLen,opts.maxLen),maxLen=Math.max(opts.minLen,opts.maxLen);const lib=library(opts);const aLock=opts.seedA?.trim()?customEntry(opts.seedA,lib):null,bLock=opts.seedB?.trim()?customEntry(opts.seedB,lib):null;const out:Blend[]=[];const seen=new Set<string>();if(!lib.length&&!aLock&&!bLock)return[];let guard=0;while(out.length<count&&guard<count*180){guard++;const a=aLock||pickWeighted(lib),b=bLock||pickWeighted(lib);if(!a||!b||a.word===b.word)continue;for(const v of variants(a,b)){if(v.name.length<minLen||v.name.length>maxLen||seen.has(v.name))continue;const score=scoreName(v.name,a,b,v.method).total;const tld=(opts.tlds.length?pick(opts.tlds):pick(TLDS))||".com";seen.add(v.name);out.push({id:`${v.name}-${v.method}-${guard}`,name:v.name,a:a.word,b:b.word,method:v.method,tld,score,categories:[...new Set([...a.categories,...b.categories])],sourcesA:a.sources,sourcesB:b.sources});if(out.length>=count)break;}}return out.sort((x,y)=>y.score-x.score)}
export const title=(w:string)=>w.charAt(0).toUpperCase()+w.slice(1);
