import type { WordSeed } from "../types";

// Generated by scripts/update-dnjournal-sales.mjs.
// The scheduled workflow refreshes this file from DNJournal annual/YTD charts.
export const DNJOURNAL_LIVE_WORDS: WordSeed[] = [];
